/**:
  ros__parameters:
    keep_instance_label:
      UNKNOWN: true
      CAR: true
      TRUCK: true
      BUS: true
      TRAILER: true
      MOTORCYCLE: true
      BICYCLE: true
      PEDESTRIAN: true

    # the maximum distance of pointcloud to be applied filter
    filter_distance_threshold: 120.0
